// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFQGO0xfxOcTnJFNrKt5Fqd1R2mGr4SSE',
    appId: '1:1095322210464:web:ba3ada048389093458f9c5',
    messagingSenderId: '1095322210464',
    projectId: 'riaaya-b06ce',
    authDomain: 'riaaya-b06ce.firebaseapp.com',
    storageBucket: 'riaaya-b06ce.firebasestorage.app',
    measurementId: 'G-WMGWBBCRKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRqiH-YwlOPgadgwTCS_UDqpNwTb1zmUU',
    appId: '1:1095322210464:android:7e170fff53f161b458f9c5',
    messagingSenderId: '1095322210464',
    projectId: 'riaaya-b06ce',
    storageBucket: 'riaaya-b06ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZkECm8X298iP_x20q_u5fybkhclszads',
    appId: '1:1095322210464:ios:5a9b9b5dc8ed12bd58f9c5',
    messagingSenderId: '1095322210464',
    projectId: 'riaaya-b06ce',
    storageBucket: 'riaaya-b06ce.firebasestorage.app',
    iosBundleId: 'com.example.riaayaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZkECm8X298iP_x20q_u5fybkhclszads',
    appId: '1:1095322210464:ios:5a9b9b5dc8ed12bd58f9c5',
    messagingSenderId: '1095322210464',
    projectId: 'riaaya-b06ce',
    storageBucket: 'riaaya-b06ce.firebasestorage.app',
    iosBundleId: 'com.example.riaayaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFQGO0xfxOcTnJFNrKt5Fqd1R2mGr4SSE',
    appId: '1:1095322210464:web:e17c1f92393a429c58f9c5',
    messagingSenderId: '1095322210464',
    projectId: 'riaaya-b06ce',
    authDomain: 'riaaya-b06ce.firebaseapp.com',
    storageBucket: 'riaaya-b06ce.firebasestorage.app',
    measurementId: 'G-4Y1ZPHLWV1',
  );
}
